[tool.black]
line-length = 119
target-version = ['py310']
include = '\.pyi?$'
skip-string-normalization = 1
force-exclude = '''
/(
  \.venv
  | migrations
)/
'''

[tool.django-stubs]
django_settings_module = "svjis.svjis.settings"
