name: Makemessages

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  makemessages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        apt-get install gettext

    - name: Make messages cs
      run: |
        source venv/bin/activate
        cd svjis
        python manage.py makemessages -l cs

    - name: Archive messages cs
      uses: actions/upload-artifact@v3
      with:
        name: Messages cs
        path: svjis/articles/locale/cs/django.po

    - name: Make messages en
      run: |
        source venv/bin/activate
        cd svjis
        python manage.py makemessages -l en

    - name: Archive messages en
      uses: actions/upload-artifact@v3
      with:
        name: Messages en
        path: svjis/articles/locale/en/django.po
